[tool.black]
line-length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
check_untyped_defs = true
pretty = true
warn_return_any = true

[tool.pylint."messages control"]
disable = ["unnecessary-lambda-assignment"]
