[tool.black]
line-length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
check_untyped_defs = true
pretty = true
warn_return_any = true

[tool.pylint.messages_control]
disable = [
  "consider-using-f-string",
  "duplicate-code",
  "invalid-name",
  "missing-module-docstring",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-branches",
  "too-many-instance-attributes",
  "too-many-lines",
  "too-many-locals",
  "too-many-public-methods",
  "unnecessary-lambda-assignment",
  "use-dict-literal",
]
extension-pkg-allow-list = ["lxml"]
recursive = true
